### ISSUE TITLE
Helm upgrade blocked by webhooks if managing policies through helm values

### ISSUE THREAD

**Issue by mrsheepuk** [appvia/terranetes-controller#1120]
**Describe the bug**
If any policies are specified in the helm chart, when running with 1 replica of the controllers, the upgrade takes that offline meaning the webhooks are no longer serviced, so the policies cannot be applied. This prevents the upgrade from succeeding, the rollback also fails for the same reason, and leaves it un-upgraded.

**To Reproduce**

Include a block like this in the values:

```
    policies:
    - name: permitted-modules
      labels: {}
      annotations: {}
      constraint:
        modules:
          allowed:
          - "https://github.com/.*"

```

and upgrade from one version to another.

**Comment by gambol99** [comment]
I created a new release https://github.com/appvia/terranetes-controller/releases/tag/v0.4.4 ... helm version v0.7.6

For testing (beyond bumping the E2E to 2 replicas now) and default to 2 replicas in the helm chart, I did the following

Build a environment

```
[jest@starfury terranetes-controller]$ make develop-environment
[jest@starfury terranetes-controller]$ cat dev/my_values.yaml  | grep -v "^#"
---
controller:
  #costs:
  #  secret: infracost-api
  #executorSecrets:
  #- bridgecrew-api
  images:
    controller: ghcr.io/appvia/terranetes-controller:ci
    executor: ghcr.io/appvia/terranetes-executor:ci
    preload: ghcr.io/appvia/terranetes-executor:ci
    policy: bridgecrew/checkov:2.3.291

policies:
  - name: permitted-modules
    labels: {}
    annotations: {}
    constraint:
      modules:
        allowed:
          - "https://github.com/.*"
```

Ensure the replicas are running 

```
[jest@starfury terranetes-controller]$ k -n terraform-system get po
NAME                                     READY   STATUS    RESTARTS       AGE
terranetes-controller-65c7dbfcc6-22fk2   1/1     Running   1 (1m ago)   1m
terranetes-controller-65c7dbfcc6-fh9l2   1/1     Running   0              1m
```

Perform a change that will take out the controllers - i.e. change the image tag from `ci` to `latest`

```
[jest@starfury terranetes-controller]$ cat dev/my_values.yaml  | grep -v "^#"
---
controller:
  #costs:
  #  secret: infracost-api
  #executorSecrets:
  #- bridgecrew-api
  images:
    controller: ghcr.io/appvia/terranetes-controller:latest
    executor: ghcr.io/appvia/terranetes-executor:latest
    preload: ghcr.io/appvia/terranetes-executor:latest
    policy: bridgecrew/checkov:2.3.291

policies:
  - name: permitted-modules
    labels: {}
    annotations: {}
    constraint:
      modules:
        allowed:
          - "https://github.com/.*"
          - "https://github.io/.*"

[jest@starfury terranetes-controller]$ k get policies.terraform.appvia.io 
NAME                AGE
permitted-modules   24m
```

Use helm to redeploy

```
[jest@starfury terranetes-controller]$ helm upgrade --install terranetes-controller ./charts/terranetes-controller --namespace terraform-system --values dev/my_values.yaml 
Release "terranetes-controller" has been upgraded. Happy Helming!
NAME: terranetes-controller
LAST DEPLOYED: Thu Nov 23 17:50:29 2023
NAMESPACE: terraform-system
STATUS: deployed
REVISION: 3
TEST SUITE: None
```

Ensure a controller is retained during the upgrade

```
[jest@starfury terranetes-controller]$ k -n terraform-system get po
NAME                                     READY   STATUS              RESTARTS   AGE
terranetes-controller-5f6bbb7c49-752vr   0/1     ContainerCreating   0          6s
terranetes-controller-5f6bbb7c49-gwqgl   0/1     ContainerCreating   0          6s
terranetes-controller-65c7dbfcc6-fh9l2   1/1     Running             0          109m
```

Ensure the new controllers come up

```
jest@starfury terranetes-controller]$ k -n terraform-system get po
NAME                                     READY   STATUS    RESTARTS   AGE
terranetes-controller-5f6bbb7c49-752vr   1/1     Running   0          12s
terranetes-controller-5f6bbb7c49-gwqgl   1/1     Running   0          12s
```
