### ISSUE TITLE
backendTemplate in providers not being used on destroy operations

### ISSUE THREAD

**Issue by paalkr** [appvia/terranetes-controller#1274]
**Describe the bug**
If you have defined a custom backend secret in a provider, this custom backend is not used during destroy (aka deleting a configuration)

**To Reproduce**
Create a provider with a `backendTemplate` and create a configuration that uses the provider. See example below

```
apiVersion: terraform.appvia.io/v1alpha1
kind: Provider
metadata:
  annotations:
    terranetes.appvia.io/default-provider: "false"
  name: aws-vk8s1
spec:
  provider: aws
  serviceAccount: aws-provider-sa
  source: injected
  summary: Manage AWS platform resources for the vk8s1 vCluster
  backendTemplate:
    name: terraform-backend-s3-vk8s1
    namespace: kube-terraform-controller
---
apiVersion: v1
kind: Secret
metadata:
  name: terraform-backend-s3-vk8s1
  namespace: kube-terraform-controller
stringData:
  backend.tf: |
    terraform {
      backend "s3" {
        bucket         = "foo-bar-states"
        key            = "geodata/vcluster/test/{{ .name }}"
        region         = "eu-north-1"
        dynamodb_table = "foo-bar-locks"
      }
    }
```

Creating resurces does work and the state is stored in the custom state store backend. However, deleting does not work, the destroy job states there are no resources to be deleted. This happens because the controller falls back to the default state backend defined in the helm chart as

```
controller:
  backend:
    name: "terraform-backend-s3"
```

```
apiVersion: v1
kind: Secret
metadata:
  name: terraform-backend-s3
stringData:
  backend.tf: |
    terraform {
      backend "s3" {
        bucket         = "bar-baz-states"
        key            = "geodata/kate/prod/{{ .name }}"
        region         = "eu-north-1"
        dynamodb_table = "bar-baz-locks"
      }
    }
```

**Expected behavior**
The backend defined with the `backendTemplate ` in the provider to be used when deleting configurations

**Additional context**
Terraneste version: 0.4.5
