### ISSUE TITLE
Namespace not found in the cache / namespace missing from cache

### ISSUE THREAD

**Issue by paalkr** [appvia/terranetes-controller#1303]
**Describe the bug**
After running for a few hours, we start to see repeated errors like this in the controller
```
{"level":"warning","msg":"namespace not found in the cache, this will cause issues on selector policies","namespace":"kube-argocd","time":"2024-03-12T08:55:50Z"}
{"error":"namespace missing from cachce","kind":"configuration","level":"error","msg":"Failed to retrieve the namespace from the cache","name":"irsa-ek8s1-kube-argocd-remote-cluster-access","namespace":"kube-argocd","time":"2024-03-12T08:55:50Z"}
```
The controller stops all processing of configurations. Restarting the controller solves the problem, and configurations are again processed. After some hours, the same error occurs, and the controller once more need to be restarted to process configurations.

**Expected behavior**
The controller to continue process configurations without requiring repeated restarts.

**Additional context**
Terranetes version 0.4.7
Helm chart version: 0.7.10
Kubernetes version: 1.28 (eks)

**Comment by gambol99** [comment]
Hi @paalkr , yep … i’ve seen this one before, i thought it was solved … i’m guessing its something to do with the TTL in the cache .. I’ll take a look

**Comment by paalkr** [comment]
Excellent, thanks. Not sure if it's related, but we do have policies with namespace filters in all the clusters where we observe the problem.

**Comment by paalkr** [comment]
Please let me know if you have any beta builds you wold like me to test. I'm more than happy to contribute with that.

**Comment by gambol99** [comment]
hi @paalkr … i’m hoping the latest merge will have fixed the fixed issue - as the resyncPeriod should keep the cache in check ..

**Comment by paalkr** [comment]
Sounds very good, looking forward to test. Thx

**Comment by paalkr** [comment]
Unfortunately, I still get errors like this with the latest release

```
{"level":"warning","msg":"namespace not found in the cache, this will cause issues on selector policies","namespace":"XXX","time":"2024-03-26T21:19:44Z"}
{"error":"namespace missing from cachce","kind":"configuration","level":"error","msg":"Failed to retrieve the namespace from the cache","name":"YYY","namespace":"XXX","time":"2024-03-26T21:19:44Z"}
```

As I mentioned we do have several providers and policies with various namespace selectors. For example, a policy like this
```
apiVersion: terraform.appvia.io/v1alpha1
kind: Policy
metadata:
  name: terranetes-extended-context
spec:
  defaults:
  - selector:
      namespace:
        matchExpressions:
          - key: vcluster.loft.sh/vcluster-name
            operator: DoesNotExist
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
            - XXX   
    variables:
      vcluster: ""
      cluster: ek8s1
      customer: foo
      solution: bar
      environment: baz
```
